name: Build and Publish Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish
        uses: docker/build-push-action@v4
        with:
          context: .  # Path to the Dockerfile context, adjust if necessary
          file: Dockerfile  # Path to the Dockerfile relative to the context
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/latest
            ghcr.io/${{ github.repository }}/v${{ github.run_number }}

      - name: Run container to list files
        run: |
          docker run --rm ghcr.io/${{ github.repository }}:latest ls -l /app/server
