version: 1
services:
  web:
    image: node:14
    buildScript: npm install
    startScript: npm start
    env:
      NODE_ENV: production
  database:
    image: postgres:15.3
    ports:
      - 5432
